import { useCallback, useEffect, useRef, useState } from 'react';
import type { Artifact, BuildRun, RuntimeProbe } from '../../shared/types';
import { api } from '../api';
import { ParameterEditor } from './ParameterEditor';
const labels: Record<BuildRun['state'], string> = { preparing: '准备构建', running: '正在执行', succeeded: '脚本执行完成', failed: '构建失败', cancelled: '已取消', interrupted: '服务中断' };
export function BuildPanel({ projectId, files, initialSource, sourceDirty, busy, published, filesChanged, editState }: { projectId: string; files: Artifact[]; initialSource: string; sourceDirty: boolean; busy: boolean; published: (path: string) => void; filesChanged: () => Promise<void>; editState: (state: { dirty: boolean; working: boolean }) => void }) {
  const [executable, setExecutable] = useState(''), [probe, setProbe] = useState<RuntimeProbe | null>(null), [checking, setChecking] = useState(false);
  const [runs, setRuns] = useState<BuildRun[]>([]), [source, setSource] = useState(initialSource), [selected, setSelected] = useState(''), [error, setError] = useState(''), [working, setWorking] = useState(false);
  const scripts = files.filter(f => /\.py$/i.test(f.name)), run = runs.find(r => r.id === selected) || runs[0], active = runs.some(r => r.state === 'preparing' || r.state === 'running');
  const edits = useRef({ dirty: false, working: false });
  const trackEdits = useCallback((state: { dirty: boolean; working: boolean }) => { edits.current = state; editState(state); }, [editState]);
  const canChangeSource = () => !edits.current.working && (!edits.current.dirty || window.confirm('切换源码会放弃尚未保存的参数修改，继续吗？'));
  useEffect(() => { let live = true; void api.runtime().then(c => { if (live) setExecutable(c.executable); }).catch(e => { if (live) setError(e.message); }); return () => { live = false; }; }, []);
  useEffect(() => { if (!source) setSource(scripts[0]?.path || ''); }, [files]);
  useEffect(() => {
    let live = true, timer: ReturnType<typeof setTimeout>;
    const refresh = async () => { try { const rows = await api.builds(projectId); if (live) setRuns(rows); } catch (e) { if (live) setError((e as Error).message); } finally { if (live) timer = setTimeout(refresh, 1500); } };
    void refresh(); return () => { live = false; clearTimeout(timer); };
  }, [projectId]);
  const inspect = async (save: boolean) => { setChecking(true); setError(''); try { setProbe(await (save ? api.saveRuntime(executable) : api.probeRuntime(executable))); } catch (e) { setError((e as Error).message); } finally { setChecking(false); } };
  const start = async (hash: string | null) => { setWorking(true); setError(''); try { const text = await api.source(projectId, source), created = await api.startBuild(projectId, source, text, hash); setSelected(created.id); setRuns(old => [created, ...old.filter(r => r.id !== created.id)]); } finally { setWorking(false); } };
  const template = async () => { if (!canChangeSource()) return; setWorking(true); setError(''); try { const result = await api.plateTemplate(projectId); await filesChanged(); setSource(result.source); } catch (e) { setError((e as Error).message); } finally { setWorking(false); } };
  return <div className="build-panel">
    <section className="build-runtime"><h3>Python 与 CadFlow 运行环境</h3><label>Python 解释器<input aria-label="构建 Python 解释器" value={executable} onChange={e => { setExecutable(e.target.value); setProbe(null); }} placeholder="Python 可执行文件绝对路径"/></label><div className="build-actions"><button className="button" disabled={checking || !executable} onClick={() => void inspect(false)}>{checking ? '正在检测…' : '检测环境'}</button><button className="button" disabled={checking || !executable} onClick={() => void inspect(true)}>检测并保存解释器</button></div>{probe && <div role="status"><strong>{probe.python ? `Python ${probe.version} · ${probe.platform}` : 'Python 不可用'}</strong><p className={probe.cadflow ? 'positive' : 'error-text'}>{probe.message}</p>{probe.cadflowVersion && <small>CadFlow {probe.cadflowVersion}</small>}</div>}<small>使用已有的本机虚拟环境；本页不安装依赖。内核检查通过后，CadFlow 建模源码才能生成真实几何。</small></section>
    <section><h3>源码与参数</h3><button className="button" disabled={busy || active || working || sourceDirty} onClick={() => void template()}>新建参数化板件</button><select aria-label="构建源码文件" value={source} disabled={working || active} onChange={e => { if (canChangeSource()) setSource(e.target.value); }}><option value="">选择 Python 文件</option>{scripts.map(f => <option key={f.path} value={f.path}>{f.path}</option>)}</select>{source && <ParameterEditor key={`${projectId}/${source}`} projectId={projectId} source={source} disabled={busy || active || working || sourceDirty} run={start} changed={filesChanged} editState={trackEdits}/ >}{active && <p>当前项目已有构建正在执行</p>}{sourceDirty && <p className="error-text">请先保存源码编辑器中的修改。</p>}<small>在项目快照的独立副本中执行，最长 10 分钟。成功产物另存到新目录，原模型保留；脚本退出成功不代表 CAD 检查通过。</small></section>
    {error && <p className="form-error" role="alert">{error}</p>}
    <section><h3>构建记录</h3><select aria-label="选择构建记录" value={run?.id || ''} onChange={e => setSelected(e.target.value)}><option value="">暂无构建</option>{runs.map(r => <option key={r.id} value={r.id}>{new Date(r.createdAt).toLocaleString()} · {r.source} · {labels[r.state]}</option>)}</select>{run && <><div className="build-run-heading"><strong>{labels[run.state]}</strong>{['preparing', 'running'].includes(run.state) && <button className="button" disabled={working} onClick={async () => { setWorking(true); try { const updated = await api.cancelBuild(projectId, run.id); setRuns(old => old.map(r => r.id === updated.id ? updated : r)); } catch (e) { setError((e as Error).message); } finally { setWorking(false); } }}>取消构建</button>}</div>{run.error && <p className="form-error">{run.error}</p>}<pre className="build-log" aria-label="构建日志">{run.truncated ? '（仅显示日志末尾）\n' : ''}{run.log || '等待执行日志…'}</pre><details><summary>运行来源</summary>{run.parameters && <><h4>本次构建参数</h4><table className="parameter-history"><thead><tr><th>参数</th><th>取值</th><th>单位</th></tr></thead><tbody>{run.parameters.values.map(p => <tr key={p.name}><td>{p.name}</td><td>{p.value}</td><td>{p.unit}</td></tr>)}</tbody></table><code>{run.parameters.path}</code><code>参数 SHA-256: {run.parameters.hash}</code></>}<code>{run.executable}</code><code>{run.source}</code><code>SHA-256: {run.sourceHash}</code><small>退出码：{run.exitCode ?? '—'} · {run.finishedAt ? `完成于 ${new Date(run.finishedAt).toLocaleString()}` : '尚未完成'}</small></details>{run.state === 'succeeded' && <><p>{run.artifacts.length} 个新增或变化的产物</p><div className="build-artifacts">{run.artifacts.map(a => <a key={a.path} href={api.buildFileUrl(projectId, run.id, a.path)} download>{a.path}<span>{(a.size / 1024).toFixed(1)} KB</span></a>)}</div><button className="button primary" disabled={working || busy || !!run.publishedRevision || !run.artifacts.length} onClick={async () => { setWorking(true); setError(''); try { const result = await api.publishBuild(projectId, run.id); setRuns(await api.builds(projectId)); published(result.path); } catch (e) { setError((e as Error).message); } finally { setWorking(false); } }}>{run.publishedRevision ? '已保存到项目' : run.published ? '完成产物保存' : '将产物另存到项目'}</button>{run.published && <code>{run.published}</code>}</>}</>}</section>
  </div>;
}
