import { useEffect, useMemo, useState } from 'react';
import type { PackageFeature, PackageInfo, PackageNode, PackageSpan } from '../scene/package';
import { SourceEditor } from './SourceEditor';
export function SceneInspector({ info, selectedNodeId, select, context }: { info: PackageInfo; selectedNodeId?: string; select: (id: string) => void; context: (text: string) => void }) {
  const [query, setQuery] = useState(''), [featureId, setFeatureId] = useState(''), [span, setSpan] = useState<PackageSpan | null>(null), [sourceId, setSourceId] = useState('');
  const [onlySelected, setOnlySelected] = useState(false), [limit, setLimit] = useState(100);
  const selected = info.nodes.find(n => n.id === selectedNodeId);
  const feature = info.features.find(f => f.id === featureId), source = info.sources.find(s => s.id === sourceId);
  const parents = useMemo(() => { const map = new Map<string | null, PackageNode[]>(); for (const node of info.nodes) { const list = map.get(node.parent) || []; list.push(node); map.set(node.parent, list); } return map; }, [info]);
  useEffect(() => { setFeatureId(''); setSpan(null); setSourceId(''); setLimit(100); }, [info.archiveHash]);
  const choose = (f: PackageFeature) => { setFeatureId(f.id); const first = f.spans[0]; setSpan(first || null); setSourceId(first?.sourceId || ''); };
  const filtered = info.features.filter(f => (!onlySelected || !selected || f.definitionIds.includes(selected.definitionId)) && `${f.label} ${f.op} ${f.id}`.toLowerCase().includes(query.toLowerCase()));
  const renderNodes = (parent: string | null, depth = 0): React.ReactNode => (parents.get(parent) || []).map(node => {
    const children = parents.get(node.id) || [];
    return <div className="scene-node" key={node.id}>{children.length ? <details open={depth < 2}><summary>{node.name} <small>{children.length} 项</small></summary>{node.meshIds.length > 0 && <button className="text-button" onClick={() => select(node.meshIds[0])}>选择此节点几何</button>}<div className="scene-children">{renderNodes(node.id, depth + 1)}</div></details> : <button className={`scene-node-button ${selectedNodeId === node.id ? 'active' : ''}`} disabled={!node.meshIds.length || !node.selectable} title={node.id} onClick={() => select(node.meshIds[0])}>{node.name}<small>{node.visible ? '' : '初始隐藏'}</small></button>}</div>;
  });
  return <div className="scene-inspector">
    <div className="scene-evidence"><strong>{info.format === 'cadflow-1.0' ? 'CadFlow Scene 1.0' : 'SimpleCADAPI 产品包 3.0'} · mm</strong><span>资源摘要已校验 · {info.nodes.length} 个节点 · {info.features.length} 个特征 · {info.sources.length} 份源码</span><span>{info.connectors} 个连接器{info.joints !== undefined ? ` · ${info.joints} 个关节` : ''}</span><details><summary>查看包与场景标识</summary><code>{info.archiveHash}</code><code>{info.revision}</code></details></div>
    <div className="scene-columns"><section aria-label="场景装配层级"><h3>装配层级</h3><div className="scene-hierarchy">{renderNodes(null)}</div>{selected && <p className="scene-note">已选择：{selected.name}<br/>定义：{selected.definitionId}</p>}</section>
    <section aria-label="场景特征"><h3>特征与依赖</h3><input aria-label="搜索场景特征" value={query} onChange={e => { setQuery(e.target.value); setLimit(100); }} placeholder="搜索名称、操作或 ID"/>{selected && <label className="scene-filter"><input type="checkbox" checked={onlySelected} onChange={e => setOnlySelected(e.target.checked)}/>只看所选零件的直接关联特征</label>}<div className="scene-feature-list">{filtered.slice(0, limit).map(f => <button key={f.id} className={featureId === f.id ? 'active' : ''} onClick={() => choose(f)}><strong>{f.label}</strong><small>{f.op} · {f.spans.length} 处源码</small></button>)}{filtered.length > limit && <button onClick={() => setLimit(n => n + 100)}>继续显示</button>}{!filtered.length && <p className="scene-note">{info.features.length ? '没有符合条件的特征。' : '此包未提供可显示的建模特征图。'}</p>}</div></section></div>
    {feature && <section className="scene-feature-detail"><h3>{feature.label}</h3><code>{feature.id}</code><div className="scene-inputs"><span>依赖：</span>{feature.inputs.length ? feature.inputs.map(id => <button className="text-button" key={id} onClick={() => choose(info.features.find(f => f.id === id)!)}>{info.features.find(f => f.id === id)!.label}</button>) : <span>无</span>}</div><details><summary>特征参数（包内记录）</summary><pre>{JSON.stringify(feature.parameters, null, 2)}</pre></details><div className="scene-span-buttons">{feature.spans.map((s, i) => <button key={i} className="button" onClick={() => { setSpan(s); setSourceId(s.sourceId); }}>{info.sources.find(v => v.id === s.sourceId)!.name}:{s.start}–{s.end}</button>)}</div><button className="button" onClick={() => context(`请检查当前场景特征：${feature.label}\n特征 ID：${feature.id}\n操作：${feature.op}\n参数：${JSON.stringify(feature.parameters)}\n场景包 SHA-256：${info.archiveHash}\n源码位置：${feature.spans.map(s => `${info.sources.find(v => v.id === s.sourceId)!.name}:${s.start}-${s.end}`).join(', ')}\n`)}>加入对话草稿</button></section>}
    <section className="scene-source"><h3>包内源码快照</h3><select aria-label="选择包内源码" value={sourceId} onChange={e => { setSourceId(e.target.value); setSpan(null); }}><option value="">选择一份源码</option>{info.sources.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select>{source ? <><p className="scene-note">只读 · {source.name}{span ? ` · 第 ${span.start}–${span.end} 行` : ''}</p><div className="scene-source-editor"><SourceEditor value={source.text} onChange={() => {}} readOnly lineRange={span ? { start: span.start, end: span.end } : undefined}/></div></> : <p className="scene-note">选择特征的源码位置，可直接定位到对应代码。</p>}</section>
  </div>;
}
