import {ThermalComparison} from './ThermalComparison';
import {useEffect,useState} from 'react';
import {request} from '../api';
import type {Artifact} from '../../shared/types';
import type {ThermalRun,ThermalProbe} from '../../shared/thermal';
import {ThermalViewer,thermalFileUrl} from './ThermalViewer';
const send=(method:string,body:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const labels:Record<ThermalRun['state'],string>={running:'正在仿真',succeeded:'仿真完成',failed:'仿真失败',cancelled:'已取消',interrupted:'服务中断'};
const initial={name:'散热评估',base_material:{name:'铝（示例）',k:205,rho:2700,cp:900,thermal_expansion_CTE_per_K:23.1e-6},analysis_mode:'transient',initial_C:25,ambient_C:25,default_h:10,duration_s:60,dt_s:2,save_s:10,mesh_size_m:.004,air_gap_enabled:false,heat_sources:[{name:'顶部热源',source_type:'surface',placement:'surface',power_W:5,start_s:0,end_s:60,selector:'+z'}]};
export function ThermalPanel({projectId,files,initialSource,busy,changed,feedback}:{projectId:string;files:Artifact[];initialSource?:string;busy:boolean;changed:()=>Promise<void>;feedback:(text:string)=>void}){
  const models=files.filter(f=>/\.(step|stp|stl)$/i.test(f.path)&&!f.path.startsWith('simulations/'));
  const [source,setSource]=useState(models.find(f=>f.path===initialSource)?.path||models[0]?.path||''),[units,setUnits]=useState('mm');
  const [executable,setExecutable]=useState(''),[probe,setProbe]=useState<ThermalProbe|null>(null),[error,setError]=useState(''),[working,setWorking]=useState(false);
  const [text,setText]=useState(JSON.stringify(initial,null,2)),[runs,setRuns]=useState<ThermalRun[]>([]),[selected,setSelected]=useState(''),[loaded,setLoaded]=useState(false);
  const run=runs.find(r=>r.id===selected)||runs[0],active=runs.some(r=>r.state==='running'),base=`/api/projects/${projectId}/thermal`;
  useEffect(()=>{let live=true;void request<{executable:string}>('/api/thermal/runtime').then(c=>{if(live)setExecutable(c.executable);}).catch(e=>{if(live)setError(e.message);});
    void request<{source?:string;units?:string;config?:unknown}>(base+'/case').then(c=>{if(!live)return;if(c.config)setText(JSON.stringify(c.config,null,2));if(c.source&&models.some(m=>m.path===c.source))setSource(c.source);if(c.units)setUnits(c.units);setLoaded(true);}).catch(e=>{if(live){setError(e.message);setLoaded(true);}});return()=>{live=false;};},[projectId]);
  useEffect(()=>{let live=true,timer:ReturnType<typeof setTimeout>;const refresh=async()=>{try{const rows=await request<ThermalRun[]>(base);if(live)setRuns(rows);}catch(e){if(live)setError((e as Error).message);}finally{if(live)timer=setTimeout(refresh,2000);}};void refresh();return()=>{live=false;clearTimeout(timer);};},[projectId]);
  const act=async(fn:()=>Promise<void>)=>{setWorking(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setWorking(false);}};
  const current=()=>({source,units,config:JSON.parse(text)});
  const save=async()=>{await request(base+'/case',send('PUT',current()));await changed();};
  const setBasic=(key:string,value:string)=>{try{const cfg=JSON.parse(text);cfg[key]=key==='analysis_mode'?value:Number(value);setText(JSON.stringify(cfg,null,2));}catch{setError('请先修正工况 JSON');}};
  let cfg:Record<string,unknown>={};try{cfg=JSON.parse(text);}catch{}
  return <div className="thermal-panel">
    <section><h3>建模 → 热仿真</h3><p>选择构建后保存到项目的 STEP/STL。每次计算保留几何副本和工况，修改模型后可重新计算并比较。</p><label>模型<select aria-label="热仿真模型" value={source} disabled={working||active} onChange={e=>setSource(e.target.value)}><option value="">选择模型</option>{models.map(f=><option key={f.path} value={f.path}>{f.path}</option>)}</select></label><label>STL 长度单位<select value={units} onChange={e=>setUnits(e.target.value)}><option value="mm">毫米</option><option value="cm">厘米</option><option value="m">米</option></select></label><small>STEP 使用文件内的单位；所有工况坐标、网格尺寸使用米。+Z 指源文件坐标的朝上表面。</small>{!models.length&&<p>先在「构建」中生成 STEP/STL，并将产物保存到项目。</p>}</section>
    <details><summary>独立热仿真环境</summary><label>Python 解释器<input aria-label="热仿真 Python 解释器" value={executable} onChange={e=>{setExecutable(e.target.value);setProbe(null);}}/></label><button className="button" disabled={working||!executable} onClick={()=>void act(async()=>{setProbe(await request<ThermalProbe>('/api/thermal/runtime',send('PUT',{executable})));})}>检测并保存环境</button>{probe&&<p className={probe.ok?'positive':'form-error'}>{probe.message} {probe.version}</p>}<small>安装 thermal-sim 的独立 Python 环境，通过版本化命令行连接。</small></details>
    <section><h3>材料与工况</h3><div className="thermal-fields"><label>分析类型<select value={String(cfg.analysis_mode||'transient')} onChange={e=>setBasic('analysis_mode',e.target.value)}><option value="transient">瞬态</option><option value="steady">稳态</option></select></label>{[['initial_C','初温 °C'],['ambient_C','环境 °C'],['default_h','对流 W/(m²·K)'],['duration_s','总时长 s'],['dt_s','计算步长 s'],['save_s','保存间隔 s'],['mesh_size_m','网格尺寸 m']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" value={String(cfg[key]??'')} onChange={e=>setBasic(key,e.target.value)}/></label>)}</div><p>默认示例：铝、顶部 5 W、环境 25 °C、60 秒。请按实际条件调整；热源启停时间在下方单独设置。</p><details open><summary>完整工况 JSON · 材料、热源、散热与结构约束</summary><textarea aria-label="热仿真工况 JSON" className="thermal-json" spellCheck={false} value={text} onChange={e=>setText(e.target.value)}/><small>表面 selector 支持 all、±x、±y、±z；按仿真网格重新定位，不复用 Studio 预览面编号。也支持点热源、多材料和上游完整 Simulation 配置。</small></details><div className="build-actions"><button className="button" disabled={working||busy||active||!loaded} onClick={()=>void act(save)}>保存工况</button><button className="button primary" disabled={working||busy||active||!source||!loaded} onClick={()=>void act(async()=>{await save();const created=await request<ThermalRun>(base,send('POST',current()));setSelected(created.id);setRuns(old=>[created,...old]);})}>{working?'正在处理…':'运行热仿真'}</button></div></section>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section><h3>结果与设计反馈</h3><select aria-label="热仿真记录" value={run?.id||''} onChange={e=>setSelected(e.target.value)}><option value="">暂无计算记录</option>{runs.map(r=><option key={r.id} value={r.id}>{new Date(r.createdAt).toLocaleString()} · {r.source} · {labels[r.state]}</option>)}</select>{run&&<><p><strong>{labels[run.state]}</strong> {run.progress?.detail}</p>{run.state==='running'&&<><progress max={100} value={run.progress?.progress||0}/><button className="button" disabled={working} onClick={()=>void act(async()=>{await request(`${base}/${run.id}/cancel`,send('POST',{}));setRuns(await request(base));})}>取消仿真</button></>}{run.stale&&<p className="form-error">当前模型已变化：本结果对应旧模型，请重新仿真。</p>}{run.error&&<p className="form-error">{run.error}</p>}{run.result&&<><div className="thermal-summary"><span>最低 <b>{run.result.result.minimum_C.toFixed(2)} °C</b></span><span>最高 <b>{run.result.result.maximum_C.toFixed(2)} °C</b></span><span>保存 <b>{run.result.result.frames} 帧</b></span></div><ThermalComparison key={`compare-${run.id}`} run={run} runs={runs}/><ThermalViewer key={run.id} projectId={projectId} run={run}/>{run.result.result.summary.warnings?.map((w,i)=><p key={i} className="hint">{w}</p>)}<div className="build-artifacts">{['job/report.pdf','job/report.md','job/history.csv','job/result.zip','manifest.json'].map(file=><a key={file} href={thermalFileUrl(projectId,run.id,file)} download>{file.split('/').pop()}</a>)}</div><div className="build-actions"><button className="button" disabled={working||busy||active||!!run.publishedRevision} onClick={()=>void act(async()=>{await request(`${base}/${run.id}/publish`,send('POST',{}));await changed();setRuns(await request(base));})}>{run.publishedRevision?'已保存到项目':'保存结果到项目'}</button><button className="button primary" disabled={working||busy||active} onClick={()=>void act(async()=>{const saved=await request<{path:string}>(`${base}/${run.id}/publish`,send('POST',{}));await changed();feedback(`请根据热仿真结果检查并改进设计。\n建模来源：${run.source}\n模型 SHA-256：${run.sourceHash}\n报告：${saved.path}/job/report.md\n工况：${saved.path}/job/config.json\n最高温度：${run.result!.result.maximum_C.toFixed(2)} °C。${run.stale?'注意：当前模型已变化，此结果仅对应旧模型。':''}\n先阅读报告、核对热边界和材料，再提出建模修改；修改后导出 STEP/STL 并重新仿真验证。`);})}>将结果加入设计对话</button><button className="button" disabled={working||active} onClick={()=>{setText(JSON.stringify(run.config,null,2));setUnits(run.units);if(models.some(f=>f.path===run.source))setSource(run.source);}}>复用本次工况</button></div></>}<details><summary>日志与来源</summary><code>{run.source}</code><code>SHA-256: {run.sourceHash}</code><pre className="build-log">{run.log||'等待执行…'}</pre></details></>}</section>
  </div>;
}
