import { createRoot } from 'react-dom/client';
import App from './App';
import './styles.css';
import './theme.css';
import './history.css';
import './step.css';
import './scene-package.css';
import './reviews.css';
import './builds.css';
createRoot(document.getElementById('root')!).render(<App/>);
